"""Render README.md for the root and every folder from catalog.jsonl (+ ratings.jsonl).

Usage:  python scripts/render.py [--check]
--check: exit 1 if any README on disk differs from what would be rendered (CI / pre-commit).
Generated files carry a header; edit catalog.jsonl / ratings.jsonl, never the READMEs.
"""
import argparse, json, sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AXES = {
    "1-image": ("🎨", "Image", "illustration, painting, photography — what a single frame can hold"),
    "2-interface-print": ("🖥", "Interface & Print", "web, type, print, presentation, social posts"),
    "3-space-object": ("🏛", "Space & Object", "architecture, installations, industrial design, fashion"),
    "4-motion-sound": ("🎞", "Motion & Sound", "VJing, mixed reality, video, music"),
    "5-culture-ideas": ("💭", "Culture & Ideas", "magazines, blogs, consciousness, discovery feeds"),
    "6-feeds": ("📰", "Feeds", "news and reading, kept for the record — not inspiration as such"),
}
STATUS = {"alive": "", "redirected": "↪", "blocked": "🛡", "moved": "🪦", "dead": "🪦", "unchecked": "·"}
VERDICT = {"core": "🔥", "take": "✅", "watch": "👀", "archive": "🧊", "reject": "✕", "keep": "🧰", "drop": "✕"}
HEADER = "<!-- generated by scripts/render.py from catalog.jsonl — do not edit by hand -->\n"


def load(name):
    p = ROOT / name
    if not p.exists():
        return []
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]


def esc(s):
    return (s or "").replace("|", "\\|").replace("[", "\\[").replace("]", "\\]").strip()


def rating_cell(r):
    if not r:
        return ""
    parts = [VERDICT.get(r.get("verdict"), "")]
    if r.get("star"):
        parts.append("⭐")
    if r.get("dims"):
        parts.append(" · ".join(r["dims"]))
    cell = " ".join(p for p in parts if p)
    if r.get("why"):
        cell += f" — {esc(r['why'])}"
    return cell


def build():
    items, ratings = load("catalog.jsonl"), {}
    for r in load("ratings.jsonl"):
        ratings[r["id"]] = r  # last line wins: ratings.jsonl is append-only
    names = {}                       # folder slug path -> display name of its last segment
    direct = defaultdict(list)       # folder -> items placed exactly there
    total = defaultdict(int)         # folder -> items in the whole subtree
    children = defaultdict(set)
    for it in items:
        parts = it["folder"].split("/")
        for i in range(1, len(parts) + 1):
            f = "/".join(parts[:i])
            total[f] += 1
            if i > 1:
                children["/".join(parts[:i - 1])].add(f)
                names[f] = it["path"][i - 2]
        direct[it["folder"]].append(it)
    for ax, (icon, title, _) in AXES.items():
        names[ax] = f"{icon} {title}"

    out = {}
    for folder in sorted(total):
        parts = folder.split("/")
        crumbs = " › ".join(names["/".join(parts[:i])] for i in range(1, len(parts) + 1))
        up = "../" * len(parts)
        lines = [HEADER, f"# {crumbs}\n", f"[← catalog]({up}README.md)"
                 + (f" · [↑ up](../README.md)" if len(parts) > 1 else "") + "\n"]
        if len(parts) == 1:
            lines.append(f"_{AXES[folder][2]}_\n")
        kids = sorted(children[folder], key=lambda f: (-total[f], names[f].lower()))
        if kids:
            lines.append("**Sections:** " + " · ".join(
                f"[{esc(names[k])}]({k.split('/')[-1]}/README.md) ({total[k]})" for k in kids) + "\n")
        rows = sorted(direct[folder], key=lambda it: (not (ratings.get(it["id"]) or {}).get("star"),
                                                      it["title"].lower()))
        if rows:
            lines += ["|   | Resource | Kind | Rating |", "|---|---|---|---|"]
            for it in rows:
                link = f"[{esc(it['title'])}]({it['url']})"
                if it.get("status") in ("dead", "moved"):
                    link += f" · [archive]({it['wayback']})" if it.get("wayback") else " · _no archive copy_"
                lines.append(f"| {STATUS.get(it.get('status'), '')} | {link} | `{it['kind']}` | "
                             f"{rating_cell(ratings.get(it['id']))} |")
            lines.append("")
        out[ROOT / folder / "README.md"] = "\n".join(lines)

    # root README
    from collections import Counter
    st = Counter(it.get("status") for it in items)
    rated = sum(1 for it in items if it["id"] in ratings)
    tree = ["```", "inspo/"]
    axes = [a for a in AXES if a in total]

    def draw(folder, prefix):
        kids = sorted(children[folder], key=lambda f: (-total[f], names[f].lower()))
        for i, k in enumerate(kids):
            last = i == len(kids) - 1
            tree.append(f"{prefix}{'└── ' if last else '├── '}{k.split('/')[-1]}/  ({total[k]})")
            draw(k, prefix + ("    " if last else "│   "))
    for j, ax in enumerate(axes):
        last = j == len(axes) - 1
        tree.append(f"{'└── ' if last else '├── '}{ax}/  ({total[ax]})")
        draw(ax, "    " if last else "│   ")
    tree.append("```")
    root = [HEADER, "# inspo\n",
            "A hand-collected library of web resources for designers, artists and makers — "
            "galleries, studios, magazines, tools — gathered over years of bookmarking and now "
            "sorted, link-checked and (gradually) rated.\n",
            f"**{len(items)} links** · {st['alive']} alive · {st['redirected']} redirected · "
            f"{st['blocked']} unverifiable (bot wall) · {st['dead'] + st['moved']} gone, with archive copies where they exist"
            f" · {rated} rated\n",
            "## Axes\n"]
    for ax in axes:
        icon, title, blurb = AXES[ax]
        root.append(f"- {icon} **[{title}]({ax}/README.md)** ({total[ax]}) — {blurb}")
    root += ["", "## Tree\n"] + tree + [
        "", "## Legend\n",
        "| mark | meaning |", "|---|---|",
        "| ↪ | redirects to another site |", "| 🛡 | the site blocks robots — not verified, probably fine |",
        "| 🪦 | gone; `archive` points to the Wayback Machine copy |", "| · | not checked yet |",
        "",
        "**Kind:** `artist` · `gallery` · `magazine` · `community` · `collection` · `reference` · "
        "`example` · `tool` · `service` · `foundry` · `gear` · `shop` · `label` · `channel` · `course`\n",
        "**Rating:** taste objects 🔥 core · ✅ take · 👀 watch · 🧊 archive · ✕ pass; "
        "utilities 🧰 keep · 🧊 archive · ✕ drop; ⭐ recommended — see [CHIPS.md](CHIPS.md)\n",
        "## How it is built\n",
        "`catalog.jsonl` is the source of truth (one link per line); `ratings.jsonl` holds the ratings. "
        "Every README is generated: `python scripts/render.py`. Links are re-checked with "
        "`python scripts/check_links.py`. The initial import came from a browser bookmarks export "
        "(`scripts/import_bookmarks.py`).\n",
        "## License\n",
        "The catalog (selection, structure, ratings) is [CC BY 4.0](LICENSE). Linked sites belong to their owners.\n"]
    out[ROOT / "README.md"] = "\n".join(root)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files = build()
    if a.check:
        stale = [str(p.relative_to(ROOT)) for p, txt in files.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != txt]
        if stale:
            print("stale READMEs:", *stale, sep="\n  "); sys.exit(1)
        print(f"ok: {len(files)} READMEs up to date"); return
    for p, txt in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(txt, encoding="utf-8", newline="\n")
    print(f"rendered {len(files)} READMEs")


if __name__ == "__main__":
    main()
